events {}

http {
brotli on;
brotli_static on;
brotli_comp_level 6;
brotli_types
    text/plain
    text/css
    text/javascript
    application/javascript
    application/x-javascript
    application/json
    application/xml
    application/xml+rss
    font/ttf
    font/otf
    image/svg+xml;

    include       mime.types;
    default_type  application/octet-stream;

    gzip on;
    gzip_disable "msie6";
    gzip_vary on;
    gzip_proxied any;
    gzip_comp_level 6;
    gzip_buffers 16 8k;
    gzip_http_version 1.1;
    gzip_min_length 256;
    gzip_types
        text/plain
        text/css
        text/javascript
        application/javascript
        application/x-javascript
        application/json
        application/xml
        application/xml+rss
        font/ttf
        font/otf
        image/svg+xml;

    server {
        listen 80;
        root /usr/share/nginx/html;
        index index.html;

        # редирект с /blog/... на blog.harmex.ru/blog/...
        location ~ ^/blog(/.*)?$ {
            return 301 https://blog.harmex.ru$request_uri;
        }

        location / {
            try_files $uri $uri/ =404;
        }

        error_page 404 /404.html;
    }
}
